import { existsSync, writeFileSync } from "node:fs";

const requiredDocs = [
  "docs/PRODUCT_PLAN.md",
  "IMPLEMENTATION_ROADMAP.md",
  "PHASE_4_FREEZE.md",
  "docs/PHASE_5_LIVE_MODE_IMPLEMENTATION_READINESS_SPRINT_PLAN.md",
];

const missing = requiredDocs.filter((path) => !existsSync(path));
if (missing.length > 0) {
  throw new Error(`Missing roadmap document(s): ${missing.join(", ")}`);
}

const graph = `# PayGate Product Roadmap Graph

Generated by \`npm run graphify\`.

\`\`\`mermaid
flowchart TD
  P[Product Objective\\nProvider-neutral multi-app payment gateway] --> G[Non-negotiable boundaries\\nHub owns commercial authority, secrets, webhooks, entitlements, reconciliation]

  G --> PH0[Phase 0\\nContract and authority freeze\\nFrozen]
  PH0 --> PH1[Phase 1\\nExecutable foundation\\nFrozen]
  PH1 --> PH2[Phase 2\\nStripe sandbox vertical slice\\nFrozen]
  PH2 --> PH3[Phase 3\\nAIntern integration\\nFrozen]
  PH3 --> PH4[Phase 4\\nProduction hardening\\nCurrent closeout]
  PH4 --> F4[Phase 4 freeze note\\nRequired before Phase 5]
  F4 --> PH5[Phase 5\\nLive-mode implementation readiness\\nPlanned, no live money]
  PH5 --> A6[Explicit operator approval\\nRequired outside source control]
  A6 --> PH6[Phase 6\\nControlled live pilot\\nFuture approval required]
  PH6 --> PH7[Phase 7\\nMulti-app scale-out\\nFuture]

  PH4 --> T41[Diagnostics auth]
  PH4 --> T42[Reconciliation inspection]
  PH4 --> T43[Admin console]
  PH4 --> T44[Multi-app onboarding checklist]
  PH4 --> T45[Live readiness checklist]
  PH4 --> T46[Monitoring baseline]
  PH4 --> T47[Provider account isolation]
  PH4 --> T48[Controlled live test gate]

  PH5 --> T51[Live adapter boundary]
  PH5 --> T52[Live provider account config]
  PH5 --> T53[Live registry strategy]
  PH5 --> T54[Live webhook boundary]
  PH5 --> T55[Refund policy and event mapping]
  PH5 --> T56[Live operator diagnostics]
  PH5 --> T57[Phase 6 entry gate]

  BLOCK[Blocked until approval\\nLive checkout, live payment, live refund, broad rollout] -.-> PH5
  BLOCK -.-> PH6
\`\`\`

## Reading The Graph

- Phase 4 must be frozen before Phase 5 implementation begins.
- Phase 5 may prepare live-mode code boundaries, but it must not run live money.
- Phase 6 is the first possible real-money pilot and requires explicit operator approval.
- Phase 7 is app scale-out after the first controlled live path is proven.
`;

writeFileSync("docs/PRODUCT_ROADMAP_GRAPH.md", graph, "utf8");
console.log("Graphified PayGate product roadmap: docs/PRODUCT_ROADMAP_GRAPH.md");